version: '3'

services:
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "database:6379"

  prometheus:
    image: microservices/prometheus
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    
  grafana:
    image: microservices/grafana
    build:
      context: ./Grafana
      dockerfile: Dockerfile
    environment:
      PrometheusUrl: "http://prometheus:9090"
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: local_development_network