apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    org_id: 1
    url: {{PrometheusUrl}}
    is_default: true
    version: 1
    editable: true
  - name: AzureMonitor
    type: grafana-azure-monitor-datasource
    access: proxy
    orgId: 1
    url: azure portal
    jsonData:
      cloudName: azuremonitor
      subscriptionId: *replace*
      tenantId: *replace*
      clientId: *replace*
      logAnalyticsDefaultWorkspace: 11111111-1111-1111-1111-111111111111
      azureLogAnalyticsSameAs: false
      appInsightsAppId: *replace*
      keepCookies: []
    secureJsonData:
      clientSecret: *replace*
      appInsightsApiKey: *replace*
    editable: true