{
 "title": "MicroServicesArchitecture Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health State",
   "type": "singlestat",
   "description": "Current system state.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "min(microservice_health)", "legendFormat": "testtest" }
   ]
  },
  {
   "title": "Component uptime indicators (per hour)",
   "type": "graph",
   "description": "Component uptimes, average for sliding windows of one hour. \nThis graph is interesting to be able to analyze \"spikes\" in downtime which would otherwise go unnoticed due to grafana / prometheus resolution. If the metric spikes down, it means downtime occured at that point.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Uptime" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(microservice_health[1h]) * 100)",
     "legendFormat": "Watchdog"
    },
    {
     "expr": "avg(avg_over_time(up{instance=\"backendforfrontend:8081\"}[1h]) * 100)",
     "legendFormat": "BFF"
    },
    {
     "expr": "avg(avg_over_time(up{instance=\"processor:9201\"}[1h]) * 100)",
     "legendFormat": "Processor"
    },
    {
     "expr": "avg(avg_over_time(up{instance=\"redis-exporter:9121\"}[1h]) * 100)",
     "legendFormat": "Redis Exporter"
    },
    {
     "expr": "avg(avg_over_time(up{app=\"watchdog\"}[1h]) * 100)",
     "legendFormat": "WatchDog"
    },
    {
     "expr": "avg(avg_over_time(redis_up{instance=\"redis-exporter:9121\"}[1h]) * 100)",
     "legendFormat": "Redis"
    }
   ]
  },
  {
   "title": "EventHub - Message received / per minute",
   "type": "graph",
   "description": "Average messages received per minute, based on last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "11111111-1111-1111-1111-111111111111"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "EntityName", "value": "EntityName" }
      ],
      "metricDefinition": "Microsoft.EventHub/namespaces",
      "metricName": "IncomingMessages",
      "resourceGroup": "ms-we-dev-msa-rg",
      "resourceName": "ms-we-dev-msa-eventhubns",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "expr": "sum(rate(processor_messagecounter[1m]) * 60)",
     "legendFormat": "Messages processed per minute (average of last 1 minutes)"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "singlestat",
   "description": "Checks the processor component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{instance=\"processor:9201\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "description": "Checks the redis component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "min(redis_up)" }
   ]
  },
  {
   "title": "BFF",
   "type": "singlestat",
   "description": "Checks the BFF component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{instance=\"backendforfrontend:8081\"})"
    }
   ]
  },
  {
   "title": "Redis exporter",
   "type": "singlestat",
   "description": "Checks the redis exporter component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{instance=\"redis-exporter:9121\"})"
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "singlestat",
   "description": "Checks the watchdog component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{instance=\"watchdog:9200\"}\t)"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "text",
   "description": "Checks the frontend component whether it is alive.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "content": "# Not implemented."
  },
  {
   "title": "Processor - Message processed / per minute",
   "type": "graph",
   "description": "Average messages processed per minute, based on last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(processor_messagecounter[1m]) * 60)",
     "legendFormat": "Messages processed per minute (average of last 1 minutes)"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "description": "Displays the current memory usage. Since we expect that all the data we store for all about 100k vehicles should never surpass couple of MB, we set this gauge to a max of 10MB to be able to monitor possible \"memory\" leaks.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "redis_memory_used_bytes" }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "description": "Displays the number of open connections to the redis component.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Redis - Command Calls / per minute",
   "type": "graph",
   "description": "Displays an number of get (mget) and set (mset) calls per minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{cmd=~\"get|mget\"} [1m])) * 60",
     "legendFormat": "get & mget"
    },
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{cmd=~\"set|mset\"} [1m])) * 60",
     "legendFormat": "set & mset"
    }
   ]
  },
  {
   "title": "BFF 5xx errors (should never happen :) )",
   "type": "graph",
   "description": "5xx errors from BFF which should never occur",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bff_http_requests_total{status=~\"5..\"}[1m]) * 60)",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "BFF Throughput (2xx, 3xx & 4xx)",
   "type": "graph",
   "description": "Displays an average of http requests for BFF",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bff_http_requests_total{status!~\"5..\"}[1m]) * 60)",
     "legendFormat": "HTTP (2xx, 3xx, 4xx) per minute"
    }
   ]
  }
 ]
}